# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Processar Arquivo de Áudio

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'URL do arquivo de áudio para processar'
        required: true
      model_name:
        description: 'Nome do modelo a ser usado (ex: htdemucs)'
        required: true
      process_method:
        description: 'Método de processamento (MDX-Net ou Demucs)'
        required: true
      original_filename:
        description: 'Nome do arquivo de áudio original para nomear o .zip'
        required: true
        
jobs:
  process-audio:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 3. Configurar cache de dependências Python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1 ffmpeg

      - name: 5. Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r ultimatevocalremovergui-master/requirements.txt

      - name: 6. Corrigir compatibilidade do PyTorch (Demucs)
        run: |
          sed -i "s/torch.load(path, 'cpu')/torch.load(path, 'cpu', weights_only=False)/g" ultimatevocalremovergui-master/demucs/states.py

      - name: 7. Criar diretórios para os modelos
        run: |
          mkdir -p ultimatevocalremovergui-master/models/Demucs_Models/v3_v4_repo
          # A pasta de parâmetros já vem com o checkout, não precisa mais ser criada aqui.
          
      - name: 8. Baixar modelos do Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download v1.0.0-models --clobber --dir temp_models
          mv temp_models/*.onnx ultimatevocalremovergui-master/models/MDX_Net_Models/
          mv temp_models/*.ckpt ultimatevocalremovergui-master/models/MDX_Net_Models/
          mv temp_models/*.th ultimatevocalremovergui-master/models/Demucs_Models/v3_v4_repo/
          mv temp_models/*.yaml ultimatevocalremovergui-master/models/Demucs_Models/v3_v4_repo/

      - name: 9. Executar separação de áudio
        run: |
          python ultimatevocalremovergui-master/run_separation.py \
            --model-name "${{ github.event.inputs.model_name }}" \
            --process-method "${{ github.event.inputs.process_method }}" \
            --audio-url "${{ github.event.inputs.audio_url }}"
      
      # --- CORREÇÃO NO NOME DO ARTEFATO ---
      - name: 10. Fazer upload dos resultados
        uses: actions/upload-artifact@v4
        with:
          # Usa o nome do arquivo original para nomear o zip
          name: ${{ github.event.inputs.original_filename }}(busted mix)
          path: ultimatevocalremovergui-master/outputs/**
